#!/bin/bash

case "`uname -s`" in
  CYGWIN*)
    cp ../../../etc/config.properties etc/config.properties
    mkdir -p logs/
    ;;
  *)
    ln -s ../../../../etc/config.properties etc/config.properties

    if [ ! -d ../../../logs ]
    then
      mkdir ../../../logs
    fi

    ln -s ../../../logs

    if [ -r ../../../etc/app.conf ]
    then
      cat ../../../etc/app.conf >> etc/app.conf
    fi
    ;;
esac
